name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: go
      run: |
        #sudo apt-get update -y
        #sudo apt -y install libpam0g-dev 
        cd src
        autoreconf -iv
        ./configure
        make
        make check
