name: C/C++ CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
    - uses: actions/checkout@v4
    - name: go
      run: |
        apt-get update -y
        apt -y install libpam0g-dev sudo autoconf
        cd src
        autoreconf -iv
        ./configure
        make
        make check
